### ISSUE TITLE
是否有 LayaAirCmdTool.max.js 的未合并源码？

### ISSUE THREAD

**Issue by vvenv** [Cola-Zhang/layaair2-cmd-plus#1]
首先，感谢您的这个项目。

关于这个文件，

https://github.com/Cola-Zhang/layaair2-cmd-plus/blob/master/ProjectExportTools/LayaAirCmdTool.max.js

请问：
 - 是针对官方 IDE 里的 `LayaAirCmdTool.max.js` 修改的吗？
 - 有分离版的源码可以提供吗？

希望得到您的回答。

**Comment by Cola-Zhang** [comment]
laya1.0有个官方的命令行 是可以导出ui的， 这个项目里是把laya1.0命令行项目中的LayaAirCmdTool.max.js代码拷贝出来，因为在2.0命令行中执行脚本出现报错，  根据报错内容 从官方2.0ide中的 LayaAirCmdTool.max.js 拷贝了大量的源码 综合调试修改得到的

**Comment by Cola-Zhang** [comment]
可以参考官方的layaair2-cmd， 目前支持了ui导出
