### ISSUE TITLE
请问如何 watch 代码变化

### ISSUE THREAD

**Issue by frostbelt** [Cola-Zhang/layaair2-cmd-plus#3]
watch src 下代码变化时自动 compile

**Comment by Cola-Zhang** [comment]
参考 gulp-watch  实现方案
监视 ts变化  执行compile命令  （自动编译ts）
监视laya assets目录变化 执行ui   （自动图集打包）

**Comment by frostbelt** [comment]
好的，用 fswatch 实现了下
