### ISSUE TITLE
大佬，请教一下你是怎么拿到layaair2-cmd的源码？

### ISSUE THREAD

**Issue by sssssssh** [Cola-Zhang/layaair2-cmd-plus#4]
大佬，请教一下你是怎么拿到layaair2-cmd的源码？我最近想搞一下游戏的持续集成，也想对这个工具二次开发，但是，暂时没啥头绪

**Comment by Cola-Zhang** [comment]
点击layaIDE 帮助 开发者工具 就可以看到 日志了 然后去目录找 一点点hack

**Comment by Cola-Zhang** [comment]
持续集成你要做的话， 导出ui脚本命令封装这时第一步
然后集成webpack 把原来编译ts那套改成webpack
再编写plugin 监视ui变化 执行导出脚本

**Comment by Cola-Zhang** [comment]
现在官方已经有工具支持了，可以直接迁移到官方平台进行二次开发，更有保证
